# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a7a7f268f52577f6927ddd937d47c9960cdcf9a47c443e3323dac8f8eb14ad101dfd032d433244e742ac6691362c317bf28f8c1f6906ab605639f428b8e439

test:
  secret_key_base: e70b0d0ce9f9ce96b7caf387a7cb37c3666008e94a42c138ebc786c615bc2746565ac6d3edccac2f2f4d9a133f59413917de6b6c894fe6bec8a344da3970a7c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
